import type { Product } from '~/shared/types/product.interface'
import { ProductStatus } from '~/shared/types/product.interface'

export const PRODUCT_LIST: Product[] = [
  {
    imagePath: '/products/1.png',
    price: 450500,
    description: 'Сlavia Nord Grand сценическое цифровое пианино',
    status: ProductStatus.Promoted,
    time: '2 дня',
    viewCount: 750,
    categoryId: 3,
    companyId: 1,
  },
  {
    imagePath: '/products/2.png',
    price: 3285000,
    description: 'Hyundai Sonata 2.0 AT, 2023, 30 км',
    status: ProductStatus.NotPromoted,
    time: '4 дня',
    viewCount: 255,
    categoryId: 4,
    companyId: 1,
  },

  {
    imagePath: '/products/3.png',
    price: 4800000,
    description: '2-к. квартира, 46 м², 1/5 эт.',
    status: ProductStatus.NotPromoted,
    time: '2 дня',
    viewCount: 255,
    categoryId: 3,
    companyId: 1,
  },
  {
    imagePath: '/products/4.png',
    price: 7500,
    description: 'Старые барабаны',
    status: ProductStatus.NotPromoted,
    time: '2 дня',
    viewCount: 255,
    categoryId: 3,
    unit: 'шт',
    companyId: 1,
  },
  {
    imagePath: '/products/5.png',
    price: 7500,
    description: 'DMX сплиттер RJ45 to 4x XLR Stairville',
    status: ProductStatus.NotPromoted,
    time: '2 дня',
    viewCount: 255,
    categoryId: 3,
    companyId: 1,
  },
  {
    imagePath: '/products/6.png',
    price: 217500,
    description: 'Мотоцикл honda',
    status: ProductStatus.NotPromoted,
    time: '2 дня',
    viewCount: 255,
    categoryId: 5,

    companyId: 1,
  },
  {
    imagePath: '/products/7.png',
    price: 17900,
    description: 'Иж юпитер 5',
    status: ProductStatus.NotPromoted,
    time: '2 дня',
    viewCount: 255,
    categoryId: 5,
    companyId: 1,
  },
  {
    imagePath: '/products/8.png',
    price: 7500,
    description: 'Пылесос кёрхер с водяным мешком для сбора пыли',
    status: ProductStatus.Hidden,
    categoryId: 6,
    companyId: 1,
  },
]
